### ISSUE TITLE
ChunkBody2D  compile link godot

### ISSUE THREAD

**Issue by hwstar2018** [lethiandev/battle-tanks#1]
Heelo. Sir
I have problem to  link ChunkBody2D library  to godot on Windows.
Please  help  me.

**Comment by lethiandev** [comment]
Hi, what kind of a problem do you have?

**Comment by hwstar2018** [comment]
The code work on  godot 3.12, but it does not work on 3.21. On 06/12/2020 21:37, Konrad Nowakowski wrote: Hi, what kind of a problem do you have? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lethiandev** [comment]
Unfortunately Godot 3.2 is not supported as the GDNative's ABI is incompatible. To fix that, you could recompile the library with newer version of the GDNative C++ bindings.

To achieve similar results to the game, maybe try this module https://github.com/GoostGD/goost as it's still maintained and fully compatible with Godot 3.2.
